### ISSUE TITLE
Hiding of process accounting information (like CPU usage)

### ISSUE THREAD

**Issue by caojioayue** [milabs/awesome-linux-rootkits#5]
how to Hiding of process accounting information (like CPU usage)

**Comment by milabs** [comment]
Could you please find some examples of doing this on github and make a pull-request so we could update this repo with new information.

**Comment by caojioayue** [comment]
> 你能不能在github上找到一些这样做的例子并提出一个pull-request，这样我们就可以用新的信息来更新这个repo。

i do not find it

**Comment by neklaf** [comment]
Although is not exactly the same that was asked by @caojioyue it's something similar:
https://github.com/gianlucaborello/libprocesshider/

**Comment by neklaf** [comment]
Hello @milabs,
this issue could be closed right?

**Comment by milabs** [comment]
yeah :)
